<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<?php if ($this->isVisible()): ?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.anythingslider.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.easing.1.2.js')?>" type="text/javascript"></script>
<?php $randnum = rand(100,9999); ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>
    <div class="anythingSlider" style="width: <?php echo $_banner->getWidth().'px'?>; height: <?php echo $_banner->getHeight().'px' ?>; margin:0px 40px 30px;" >
		<div class="wrapper-slider"  >
		<ul>
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php foreach ($_banner_items as $_banner_item): ?>
				<li>
					<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
					<?php if ($_banner_item->getImage()): ?>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" 
								width="<?php echo $_banner->getWidth().'px'?> " 
								height=" <?php echo $_banner->getHeight().'px'?>" 
								alt="<?php echo $_banner_item->getContent()?>"/>
						<?php elseif ($_banner_item->getImageUrl()): ?>
						<img src="<?php echo $_banner_item->getImageUrl() ?>" 
								width="<?php echo $_banner->getWidth().'px'?> " 
								height=" <?php echo $_banner->getHeight().'px'?>" 
								alt="<?php echo $_banner_item->getContent()?>" />
						<?php endif; ?>
					</a>    
						<?php endforeach ?>
				</li>
			</ul>
		</div>
    </div>
<script type="text/javascript">
var $j<?php echo $randnum;?> = jQuery.noConflict(); 		
        function formatText(index, panel) {
		  return index + "";
	    }
    
        $j<?php echo $randnum;?>(function () {
            $j<?php echo $randnum;?>('.anythingSlider').anythingSlider({
                easing: "easeInOutExpo",        				// Anything other than "linear" or "swing" requires the easing plugin
                autoPlay: true,                 				// This turns off the entire FUNCTIONALY, not just if it starts running or not.
                delay: <?php echo $_banner->getDelay(); ?>,     // How long between slide transitions in AutoPlay mode
                startStopped: false,           					// If autoPlay is on, this can force it to start stopped
                animationTime: 600,            					// How long the slide transition takes
                hashTags: true,                					// Should links change the hashtag in the URL?
                buildNavigation: true,         					// If true, builds and list of anchor links to link to each slide
        		pauseOnHover: true,           					// If true, and autoPlay is enabled, the show will pause on hover
        		startText: "Go",                				// Start text
		        stopText: "Stop",              					// Stop text
		        navigationFormatter: formatText 				// Details at the top of the file on this use (advanced use)
            });
            
            $j<?php echo $randnum;?>("#slide-jump").click(function(){
                $j<?php echo $randnum;?>('.anythingSlider').anythingSlider(6);
            });
            
        }); 
</script>
<?php endif; ?>
<?php endif;?>
