<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<?php if ($this->isVisible()): ?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/coin-slider.js')?>" type="text/javascript"></script>
<?php $randnum = rand(100,9999); ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>
<div id="games" style="padding:0px; position: relative; background:none ;" >
	<?php $_banner_items = $this->getBannerItems(); ?>
	<?php foreach ($_banner_items as $_banner_item): ?>
	
		<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
		<?php if ($_banner_item->getImage()): ?>
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" 
						width="<?php echo $_banner->getWidth().'px'?> ; " 
						height=" <?php echo $_banner->getHeight().'px'?> " 
						alt="<?php echo $_banner_item->getContent()?>"/>
			<?php elseif ($_banner_item->getImageUrl()): ?>
				<img src="<?php echo $_banner_item->getImageUrl() ?>" 
						width="<?php echo $_banner->getWidth().'px'?> " 
						height=" <?php echo $_banner->getHeight().'px'?>" 
						alt="<?php echo $_banner_item->getContent()?>" />
			<?php endif; ?>
		</a>    
			<?php endforeach ?>  
</div>
	<script type="text/javascript">
var $j<?php echo $randnum;?> = jQuery.noConflict(); 

$j<?php echo $randnum;?>(document).ready(function() {
	$j<?php echo $randnum;?>('#games').coinslider({ hoverPause: false,
							  width:<?php echo $_banner->getWidth() ?>,
							  height:<?php echo $_banner->getHeight() ?>
	});
});
</script>		
<?php endif; ?>
<?php endif;?>
