<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/easySlider1.5.js')?>" type="text/javascript"></script>

<?php if ($this->isVisible()): ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>

<div id="content_slider" style="width: <?php echo $_banner->getWidth().'px'?>;">	
	<div id="slider" style="width: <?php echo $_banner->getWidth().'px'?>; height: <?php echo $_banner->getHeight().'px' ?>; ">
		<ul>	
			<?php $_banner_items = $this->getBannerItems(); ?>
			<?php foreach ($_banner_items as $_banner_item): ?>
			<li style="width: <?php echo $_banner->getWidth().'px'?>; height: <?php echo $_banner->getHeight().'px' ?>; ">
				<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
			<?php if ($_banner_item->getImage()): ?>
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="<?php echo $_banner_item->getContent()?>"/>
			<?php elseif ($_banner_item->getImageUrl()): ?>
				<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="<?php echo $_banner_item->getContent()?>" />
			<?php endif; ?>
				 </a>  
			</li>
			<?php endforeach ?>
		</ul>
	</div>
</div>
<?php endif; ?>	
<script type="text/javascript">
	jQuery.noConflict(); 
	jQuery(document).ready(function(){	
		jQuery("#slider").easySlider({
			auto: true,
			pause: <?php echo $_banner->getDelay(); ?>,
			continuous: true 
		});
	});	
</script>

<?php endif;?>
