<?php if (Mage::getStoreConfig('easybanner/info/enabled')&& $this->isVisible()):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/feature-gallery.js')?>" type="text/javascript"></script>
<?php $_banner = $this->getBanner(); ?>
<script type="text/javascript">
	jQuery.noConflict(); 
	jQuery(document).ready(function() {
			jQuery.featureList(
				jQuery("#tabs li a"),
				jQuery("#output li"), {
					start_item:1
				}
			);
		});
</script>
 <?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>
<div class="style_feature" style="width: <?php echo ($_banner->getWidth()).'px'?>;"><img src="<?php echo $this->getSkinUrl('images/feature-gallery/top_slide.png') ?>" alt=""/></div>
<div id="feature_list" style="width: <?php echo ($_banner->getWidth()).'px'?>;height: <?php echo $_banner->getHeight().'px' ?>;" >

	<ul id="output" style="width: <?php echo ($_banner->getWidth() - 270).'px'?>;">
	  <?php $_banner_items = $this->getBannerItems(); ?>
	  <?php foreach ($_banner_items as $_banner_item): ?>
		<li >
		 <?php if ($_banner_item->getImage()): ?>
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>"  alt="easybanner" style="width: <?php echo ($_banner->getWidth() - 270).'px'?>;height: <?php echo $_banner->getHeight().'px' ?>;"/>
		 <?php elseif ($_banner_item->getImageUrl()): ?>
			<img src="<?php echo $_banner_item->getImageUrl()?>" style="width: <?php echo ($_banner->getWidth() - 270).'px'?>;height: <?php echo $_banner->getHeight().'px' ?>;" alt="easybanner" />
		 <?php endif; ?>
			<a href="<?php echo $_banner_item->getLinkUrl(); ?>"><?php echo $this->__('Details') ?></a>
			
		</li>
		<?php endforeach ?>
	 </ul>
	 
	<ul id="tabs" style="height: <?php echo $_banner->getHeight().'px' ?>;">  
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php foreach ($_banner_items as $_banner_item): ?>
		<?php if ($_banner_item->getThumbImage()): ?>
			<li>
				<a>
					<img src="<?php echo $this->helper('easybanner/image')->init($_banner_item->getThumbImage())->resize(50, 50) ?>" alt="easybanner"/>
					<h3><?php echo $_banner_item->getTitle(); ?></h3>
					<span><?php echo substr($_banner_item->getContent(),0,30)."..." ;?></span>
				</a>
			</li>
		<?php elseif ($_banner_item->getThumbImageUrl()): ?>
			<li>
				<a>
					<img src="<?php echo $_banner_item->getThumbImageUrl() ?>" />					
					<h3><?php echo $_banner_item->getTitle(); ?></h3>
					<span><?php echo $_banner_item->getContent(); ?></span>
				</a>
			</li>
		<?php elseif ($_banner_item->getImage()): ?>
			<li>
				<a>
					<img src="<?php echo $this->helper('easybanner/image')->init($_banner_item->getImage())->resize(50, 50) ?>" alt="easybanner"/>
					<h3><?php echo $_banner_item->getTitle(); ?></h3>
					<span><?php echo $_banner_item->getContent(); ?></span>
				</a>
			</li>
		<?php endif; ?>			 
		<?php endforeach ?>
	</ul>
</div>
<div class="style_feature" style="width: <?php echo ($_banner->getWidth()).'px'?>;">
	<img src="<?php echo $this->getSkinUrl('images/feature-gallery/bottom_slide.png') ?>" alt=""/>
</div>
<?php endif; ?>