<?php if (Mage::getStoreConfig('easybanner/info/enabled')&& $this->isVisible()):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery-ui.min.js')?>" type="text/javascript"></script>
<!-- InstanceBeginEditable name="head" -->
<?php $random = rand(1000,99999); ?>
<?php $_banner = $this->getBanner(); ?>
 <?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>

	<div id="featured" style="width: <?php echo $_banner->getWidth().'px'?>; height: <?php echo $_banner->getHeight().'px' ?>; "> 
		 <ul class="ui-tabs-nav">
	  
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php $i =0;?>
		<?php foreach ($_banner_items as $_banner_item): ?>
		<?php if ($_banner_item->getThumbImage()): ?>
			<li class="ui-tabs-nav-item ">
				<a href="#fragment-<?php echo $i?>">
					<img src="<?php echo $this->helper('easybanner/image')->init($_banner_item->getThumbImage())->resize(80, 50) ?>" alt="easybanner"/>
					<span><?php echo $_banner_item->getTitle(); ?></span>
				</a>				
			</li>
		<?php elseif ($_banner_item->getThumbImageUrl()): ?>
			<li class="ui-tabs-nav-item ">
				<a href="#fragment-<?php echo $i?>">
					<img src="<?php echo $_banner_item->getThumbImageUrl() ?>" />
					<span><?php echo $_banner_item->getTitle(); ?></span>
				</a>
			</li>
		<?php elseif ($_banner_item->getImage()): ?>
			<li class="ui-tabs-nav-item">
				<a href="#fragment-<?php echo $i?>">
					<img src="<?php echo $this->helper('easybanner/image')->init($_banner_item->getImage())->resize(80, 50) ?>" alt="easybanner"/>
					<span><?php echo $_banner_item->getTitle(); ?></span>
				</a>				
			</li>
		<?php endif; ?>	
		 <?php $i ++;?>
		<?php endforeach ?>
	   
	  </ul>
  
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php $i = 0;?>
	    <?php foreach ($_banner_items as $_banner_item): ?>
		<div id="fragment-<?php echo $i?>" >
		 <?php if ($_banner_item->getImage()): ?>

			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner"/>
			 <div class="info" >

				 <?php elseif ($_banner_item->getImageUrl()): ?>
					<img src="<?php echo $_banner_item->getImageUrl()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner" />
				 <?php endif; ?>

					<h2><a href="<?php echo $_banner_item->getLinkUrl(); ?>"><?php echo $_banner_item->getTitle(); ?></a></h2>
					<p><?php echo $_banner_item->getContent(); ?></p>
			</div>
		</div>
		<?php $i ++;?>
	    <?php endforeach ?>
	  
	</div>
  
<?php endif; ?>
<script type="text/javascript">
	$j<?php echo $random;?>=jQuery.noConflict(); 
	$j<?php echo $random;?>(document).ready(function(){
		$j<?php echo $random;?>("#featured > ul").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 5000, true);
		//jQuery("#featured").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 5000, true);
		
	});
</script>