<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.pikachoose.js')?>" type="text/javascript"></script>

<?php if ($this->isVisible()): ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>
<div id="pikachoose" class="pikachoose" style="width:<?php echo $_banner->getWidth().'px'?>; display:none;" >
<ul id="pikame" >		 
	<?php $_banner_items = $this->getBannerItems(); ?>
	<?php foreach ($_banner_items as $_banner_item): ?>
	<li>
		<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
			<?php if ($_banner_item->getImage()): ?>
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner"/>
			<?php elseif ($_banner_item->getImageUrl()): ?>
				<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner" />
			<?php endif; ?>
			</a>  
			<span><?php echo $_banner_item->getTitle(); ?></span>	
	</li>
		<?php endforeach ?>
		<?php endif; ?>
</ul>
</div>
<script type="text/javascript">
  var $j = jQuery.noConflict();
	$j(document).ready(
	function (){
		$j("#pikame").PikaChoose({auto_play:true});
    $j('#pikachoose').fadeIn(1500);		
	}	
	); 
</script>
<?php endif;?>
