<?php if (Mage::getStoreConfig('easybanner/info/enabled')&& $this->isVisible()):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.pliable-0.1.0.js')?>" type="text/javascript"></script>
<?php $random = rand(1000,99999); ?>
<!-- InstanceBeginEditable name="head" -->
<?php $_banner = $this->getBanner(); ?>
 <?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>
<div class="gallery_pliable" style="width:<?php echo $_banner->getWidth().'px'?>;height:<?php echo $_banner->getHeight().'px'?>;">
	<img src="" class="primary" alt="" />
	
	<img src="<?php echo $this->getSkinUrl('images/example_images/vignette.png') ?>" class="vignette_src" alt=""/>
	<div class="scroll_up">		
		<img src="<?php echo $this->getSkinUrl('images/example_images/arrow_up.png') ?>" alt=""/>
	</div>	
	<div class="previews">		 
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php foreach ($_banner_items as $_banner_item): ?>		
				<?php if ($_banner_item->getImage()): ?>
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner"/>
				<?php elseif ($_banner_item->getImageUrl()): ?>
					<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner" />
				<?php endif; ?>				
		<?php endforeach ?>
			
		<div class="outro">
		</div>	
	</div>	
	<div class="scroll_down">		
		<img src="<?php echo $this->getSkinUrl('images/example_images/arrow_down.png') ?>" alt=""/>
	</div>
</div> 
<?php endif; ?>
<script type="text/javascript">
	$j<?php echo $random;?>=jQuery.noConflict(); 
$j<?php echo $random;?>('.gallery_pliable').ply();
</script>










