<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.cycle.js')?>" type="text/javascript"></script>

<?php if ($this->isVisible()): ?>
	<?php $_banner = $this->getBanner(); ?>
	<?php if ($_banner->getShowTitle()==1): ?>
		<h3><?php echo $_banner->getTitle(); ?></h3>
	<?php endif; ?>
	<div class="mw_easybn_simplesld2">
		<div id="slideshow" style="width: <?php echo $_banner->getWidth().'px'?>; height: <?php echo $_banner->getHeight().'px' ?>; ">   
			<?php $_banner_items = $this->getBannerItems(); ?>
			<?php foreach ($_banner_items as $_banner_item): ?>
				<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
					<?php if ($_banner_item->getImage()): ?>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="<?php echo $_banner_item->getContent()?>"/>
					<?php elseif ($_banner_item->getImageUrl()): ?>
						<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="<?php echo $_banner_item->getContent()?>" />
					<?php endif; ?>
				</a>    
			<?php endforeach ?>
		</div>
	
		<div class="aaa" style="width: <?php echo $_banner->getWidth().'px'?>;">
			<div class="bbb" style="width: <?php echo $_banner->getWidth().'px'?>;">
				<div class="so" style="width: <?php echo $_banner->getWidth().'px'?>;">
					<a href="#">
						<span id="prev"> 	
							<img src="<?php echo $this->getSkinUrl('images/sliderbanner/arrow_01.gif') ?>" alt=""/>
						</span> 
					</a>
					<ul id="nav1"></ul>
					<a href="#">
						<span id="next">
							<img src="<?php echo $this->getSkinUrl('images/sliderbanner/arrow_02.gif') ?>" alt=""/>
						</span> 		
					</a>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
<?php endif; ?>
<script type="text/javascript">

jQuery.noConflict(); 
jQuery(document).ready(function(){
		jQuery(function() {

    jQuery('#slideshow').cycle({
        
        timeout:<?php echo $_banner->getDelay(); ?>,
        prev:    '#prev',
        next:    '#next',
        pager:   '#nav1',
        pagerAnchorBuilder: pagerFactory
    });
	
    function pagerFactory(idx, slide) {
        var s = idx > 3 ? ' style="display:none"' : '';
        return '<li'+s+'><a href="#">'+(idx+1)+'</a></li>';
    };
    
});
});


</script>
