<div id="latest-facebok" class="">
    <h2><?php echo $this->__('Latest From Facebook') ?></h2>
    <div class="footer-facebook">&nbsp;</div>
    <p class="more-facebook"><a href="http://www.facebook.com/PhdCleanse" target="_blank"><?php echo $this->__('View more on ') ?>
            <img src="<?php echo $this->getSkinUrl('images/facebook_logo.jpg') ?>" alt="Facebook" width="75px" />
        </a></p>
</div>