<div id="therapy-content">
	<div id="therapy-left" class="col-1 therapy-col">
	
	<h2 class="green">Therapy Juices</h2>
	<p>The Therapy range of single-serve (350ml) raw juices are the convenient way you get your daily fix of delicious, cold-crafted juices.  Low-carb and packed full vitamins & minerals, there is no denying the goodness that comes from locally sourced fresh produce.</p>
	
<p>Keep a 6-pack of Therapy in your fridge at home or work and you are perfectly placed to:</p>
<ul><li>kick-start your day with a bottle of Therapy Green</li>
<li>prepare yourself for the full PHD Cleanse</li>
<li>deal to those mid-morning coffee cravings with Therapy Yellow</li>
<li>avoid sneaky visits to the pantry</li>
<li>honour your body after your yoga or gym workout
</li>
</ul>
	</div>
	<div id="therapy-right" class="col-2 therapy-col">
	
	<h2 class="green">Our Process</h2>
	<img src="http://phdtest.webcoclients.co.nz/skin/frontend/default/therapy/images/machine.jpg" title="Pure Health Delivered - Therapy Juices" />
	<p>The Therapy juice high pressure process (HPP) cold pasteurisation process uses only pure, cool, pressurised water - nothing else, no heat treatment, no additives, no preservatives, nothing artifical, clean on the environment, no waste and no fuss. In fact the HPP process used by us is recognised as one of the safest food safety processes in the world today.</p>
	
	</div>
</div>