
<div class="stores-links-container clearer">
    <h2><span><?php echo $this->__('Favourites') ?></span></h2>
    <ul class="stores-list">
        <li class="first">
            <a href="/cleanses-34/cleanses.html"><img src="<?php echo $this->getSkinUrl('images/stores_phdcleanse.jpg') ?>" alt="<?php echo $this->__('PHD Cleanse Systems') ?>" /></a>
            <p class="a-center"><a href="/phdcleanse/" title="<?php echo $this->__('PHD Cleanse Systems') ?>"><?php echo $this->__('PHD Cleanse Systems') ?></a> </p>
        </li>
        <li>
            <a href="/juices.html"><img src="<?php echo $this->getSkinUrl('images/stores_therapy.jpg') ?>" alt="<?php echo $this->__('Therapy Raw Juices') ?>" /></a>
            <p class="a-center"><a href="/therapy/" title="<?php echo $this->__('Therapy Raw Juices') ?>"><?php echo $this->__('Therapy Raw Juices') ?></a> </p>
        </li>
        <li class="last">
            <a href="/phd-pantry.html"><img src="<?php echo $this->getSkinUrl('images/pantry.jpg') ?>" alt="<?php echo $this->__('PHD Pantry') ?>" /></a>
            <p class="a-center"><a href="#" title="<?php echo $this->__('PHD Pantry') ?>"><?php echo $this->__('PHD Pantry') ?></a></p>
        </li>
    </ul>
</div>