<div class="featured-box">
	<a href="<?php echo Mage::getBaseUrl()?>phd-group">
		<h2 class="blue">Cleanse With Friends</h2>
	</a>
	<p>
		Save up to <strong>15% off</strong> by getting your friends and collegues to join you.
	</p>
	<a href="<?php echo Mage::getBaseUrl()?>phd-group"><img src="<?php echo $this->getSkinUrl();?>images/cleanse-with-friends-start-today.jpg" alt="PHD Group" /></a>
</div>
<div class="featured-box">
	<a href="<?php echo Mage::getBaseUrl()?>juice-cleansing">
		<h2 class="pink">About Juice Cleansing</h2>
	</a>
	<p>
		Read all about the benefits of a <strong>raw</strong> juice diet.<a class="pink" href='#'>Find Out More</a> 
	</p>
	<a href="<?php echo Mage::getBaseUrl()?>juice-cleansing"><img src="<?php echo $this->getSkinUrl();?>images/about-juice-cleansing.jpg" width="220" height="160" alt="Juice Cleansing" /></a>
</div>