<?php
/**
 * DeleteAnyOrder extension for Magento 
 *
 * @package     Yireo_DeleteAnyOrder
 * @author      Yireo.com
 * @copyright   Copyright (c) 2010 Yireo.com
 * @license     DeleteAnyOrder EULA (www.yireo.com)
 */
?>
<?php
$analysis = $this->getAnalysis();
$increments = $this->getIncrementIds();
$header = $this->__('Analysis of order-objects');
?>
<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:40%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader($header); ?></h3></td>
        <td class="formbuttons" align="right">
            <?php echo $this->getChildHtml('back_button'); ?>
            <?php echo $this->getChildHtml('cleanup_button'); ?>
        </td>
	</tr>
</table>
</div>

<form action="<?php echo $this->getCleanupUrl() ?>" method="post" id="deleteanyorder_analyze_form" enctype="multipart/form-data">
<input type="hidden" name="cleanup" value="1" />
<?php echo $this->getBlockHtml('formkey')?>
</form>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->__('Order records'); ?></h4>
    </div>
    <div class="fieldset">
        <table>
            <tr>
                <th width="300"><?php echo $this->__('Class'); ?></th>
                <th><?php echo $this->__('Obsolete entries'); ?></th>
            </tr>
            <?php foreach($analysis as $name => $value) { ?>
            <tr>
                <td><?php echo $name; ?></td>
                <td><?php 
                    if(!empty($value) && is_array($value)) {
                        echo '<strong>'.count($value).'</strong>'; 
                    } elseif(!empty($value)) {
                        echo '<strong>'.$value.'</strong>'; 
                    } else {
                        echo 0;
                    }
                ?></td>
            </tr>
            <?php } ?>
        </table>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->__('Increment IDs'); ?></h4>
    </div>
    <div class="fieldset">
        <table>
            <tr>
                <th width="200"><?php echo $this->__('Type'); ?></th>
                <th width="200"><?php echo $this->__('Current ID'); ?></th>
                <th><?php echo $this->__('Latest ID'); ?></th>
            </tr>
            <tr>
                <td><?php echo $this->__('Order'); ?></td>
                <td><?php echo $increments['current']['order']; ?></td>
                <td><?php echo $increments['last']['order']; ?></td>
            </tr>
            <tr>
                <td><?php echo $this->__('Order Invoice'); ?></td>
                <td><?php echo $increments['current']['invoice']; ?></td>
                <td><?php echo $increments['last']['invoice']; ?></td>
            </tr>
            <tr>
                <td><?php echo $this->__('Order Credit Memo'); ?></td>
                <td><?php echo $increments['current']['creditmemo']; ?></td>
                <td><?php echo $increments['last']['creditmemo']; ?></td>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var deleteanyorderForm = new varienForm('deleteanyorder_analyze_form');
</script>

