<?php
/**
 * DeleteAnyOrder extension for Magento 
 *
 * @package     Yireo_DeleteAnyOrder
 * @author      Yireo.com
 * @copyright   Copyright (c) 2010 Yireo.com
 * @license     DeleteAnyOrder EULA (www.yireo.com)
 */
?>

<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:80%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader('Overview'); ?></h3></td>
        <td class="formbuttons"></td>
	</tr>
</table>
</div>

<div class="entry-edit">
    <?php echo $this->getGridHtml(); ?>
</div>

<div class="version">
DeleteAnyOrder version <?php echo $this->getVersion(); ?>
</div>

<script type="text/javascript">
var deleteanyorderForm = new varienForm('deleteanyorder_edit_form');
function doSubmit() {
    deleteanyorderForm.submit();
    return true;
}
function doAnalyze() {
    document.location = '<?php echo $this->getAnalyzeUrl(); ?>';
    return true;
}
</script>
