<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Customer Redemption catalog
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
$numProducts = $this->getNumProducts();
?>
<div class="box-account box-info mypoints-redeemcatalog" align="center" <?php if (!Mage::getStoreConfigFlag('rewards/display/showSendPointsToAFriend')): ?>style="float:none;" <?php endif; ?>>
    <div class="box-head">
        <h2><?php echo $this->__('Use your points on any of these products') ?></h2>
    </div>
    <?php $products = $this->selectRandomProductsWithRedemptions($numProducts); ?>
    <?php if (count($products) > 0): ?>
        <?php // Grid Mode ?>
        <?php $_collectionSize = count($products) ?>
        <?php $_columnCount = 3; ?>
        <?php $i=0; foreach ($products as $product): ?>
            <?php if ($i++%$_columnCount==0): ?>
            <div class="listing">
                <ul class="products-grid">
            <?php endif ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <p class="product-image">
                        <a href="<?php echo $product->getProductUrl() ?>"
                           title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>">

                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(150); ?>"
                                 width="150" height="150"
                                 alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"
                                 title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" />
                        </a>
                    </p>
                    <p>
                        <a href="<?php echo $product->getProductUrl() ?>"
                           title="<?php echo $this->htmlEscape($product->getName()) ?>">
                            <?php echo $this->htmlEscape($product->getName()) ?>
                        </a><?php echo $this->getPointsOptimizer($product); ?>
                    </p>
                </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
            </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

    <?php else: ?>
        <div class="noproducts">
            <?php echo $this->__('There are currently no products you can purchase using your points.'); ?>
        </div>
    <?php endif; ?>
</div>