<div class="product-img-sml">
<ul class="small-pro">
<li>
<div class="pro-list-small">
<a href="#advanced-green">
<h3>20 X <img src="<?php echo $this->getSkinUrl('images/phd-cleanse-green.jpg')?>" alt="PHD Cleanse &mdash; Pure Green" /></h3>
<h4>Pure Green</h4>
</a>
</div>
</li>
<li>
<div class="pro-list-small">
<a href="#advanced-zesty-lemonade">
<h3>5 X <img src="<?php echo $this->getSkinUrl('images/phd-cleanse-orange.jpg')?>" alt="" /></h3>
<h4>Zesty Lemonade</h4>
</a>
</div>
</li>
<li>
<div class="pro-list-small">
<a href="#advanced-cashew-dream">
<h3>5 X <img src="<?php echo $this->getSkinUrl('images/product_tiny_white.jpg') ?>" alt="" /></h3>
<h4>Cashew Dream</h4>
</a>
</div>
</li>
</ul>
</div>