<?php
/**
 * Advance FAQ Management Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Advance FAQ Management
 * @author     Kamran Rafiq Malik <support@fmeextensions.com>
 *                          
 * 	       Asif Hussain <support@fmeextensions.com>
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */
?>
<?php

$faqs = $this->getFaqs();

$num_of_faqs = count($faqs);

$allowed_rating_customers = Mage::getStoreConfig('faqs/rating/allow_customers');

//Faqs that already has been rated, in that session
$faqs_already_rated = Mage::getSingleton('customer/session')->getRatedFaqsId();


?>

<?php if(Mage::getStoreConfig('faqs/rating/enable')) : ?>
	<script type="text/javascript">
	
		Event.observe(window, 'load', function() {
			
			var faq = '<?= $num_of_faqs; ?>';
			//var is_rated = '<?= $is_rated; ?>';
			
			
				for(f=1; f<=faq; f++){
					
					var rating_element = $('rating_'+f);
					if($('has_rated_'+f) != undefined){
						var is_rated = $('has_rated_'+f).readAttribute('title');
						if(is_rated == 'yes') is_rated = true;
						else if(is_rated == 'no') is_rated = false;
					}
					if(rating_element != undefined){
						
							rating = new Control.Rating(rating_element,
									{
										rated: is_rated,
										value: parseFloat($('stars_'+f).readAttribute('title')),
										faq_id: parseInt($('faq_id_'+f).readAttribute('title')),
										updateUrl:'<?php echo $this->getUrl('*/*/rating') ?>',
										updateOptions : {
											method: 'post',
											onSuccess: function(transport) {
												$('rating-success').appear();
												$('rating_message').update(transport.responseText);												
												},
											onFailure: function(transport) {
												$('rating-fail').appear();
												$('rating_message').update(transport.responseText);
												}
											}
									});
					}			
				}			
		});
	</script>

<?php endif; ?>


<?php
	$current_theme = Mage::getStoreConfig('faqs/themes/select_theme');
	if($current_theme == ''){
			
			$current_theme = 'theme1';
	}	
?>

<?php if($current_theme == 'theme1' || $current_theme == 'theme3' || $current_theme == 'theme4'):?> <style type="text/css">.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/faqs/rating.png'); ?>") !important; </style> <?php endif; ?>

<?php if($current_theme == 'theme2' || $current_theme == 'theme5'):?> <style type="text/css">.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/faqs/rating2.png'); ?>") !important; </style> <?php endif; ?>


<?php if(Mage::getStoreConfig('faqs/list/enable_accordion')) : ?>

<script type="text/javascript">
	
	Event.observe(window, 'load', function() {
		
		var default_accor_open = $('default_accordion_opened');
		if(default_accor_open != undefined){
			new Accordion('accordion-container',default_accor_open.title);
		}else{
				accordian = new Accordion('accordion-container',1);
		}
	});
	
</script>

<?php endif; ?>




<div id="wrapper">

<div class="page-title">
	<h1>
		
		<?php
			if(Mage::getStoreConfig('faqs/list/page_title') != '')
				
				echo Mage::getStoreConfig('faqs/list/page_title');
			else
				echo Mage::helper('faqs')->__('FAQ\'s Categories');
		?>
	</h1>
</div>


<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	
	<div class="success-msg" id="rating-success" style="display:none;"><p id="rating_message"></p></div>
	<div class="error-msg" id="rating-fail" style="display:none;"><p id="rating_message"></p></div>
<?php $topics_all = getAllTopics();?>	
	<div class="faq-left-container" style="">
	<ul>
	<li class="head"><h5 class="namebold"> FAQ Categories </h5></li>
	<? $i=0; ?>  
		<?php foreach ($topics_all as $_topic){ ?>
		<?php ++$i ?>
		<li class="<?php echo 'faq-list'.$i?>">
		<a href="<?php echo Mage::helper('faqs')->getUrl($_topic['identifier']); ?>"><?php echo $_topic["title"]; ?></a>
		</li>
		<?php } ?>
	</ul>
	</div>	
<?php if (!isset($faqs[0]['faqs_id'])) : ?>
	<p><?php echo $this->__('No Faqs Found in this topic!'); ?></p>
<?php else : ?>
    <div class="<?php echo $current_theme; ?>" id="accordion-container">
	
	<h1><?php if($faqs[0]["cat"] != ''){ echo $faqs[0]["cat"]; } ?></h1>
	
	<ul>
		<?php $i=0; $has_default_opened = '';
		
		foreach ($faqs as $_faqs): $i++; ?>
		<li>	
		
			<?php if($_faqs['accordion_opened'] == 1 && $has_default_opened == ''):  ?>
					<span id="default_accordion_opened" title="<?php echo $i; ?>" style="display:none;">
						<?php $has_default_opened = 'yes'; ?>
					</span>
			<?php endif; ?>
							
			<div class="accordion-toggle"><?php echo $_faqs["title"]; ?></div>
			<div class="accordion-content">
				
				<div class=""><p><?php echo $_faqs["faq_answar"]; ?></p></div>
		
				<?php if(Mage::getStoreConfig('faqs/rating/enable')) : ?>
					<div class="rating_dv">											
						<span id="<?php echo 'faq_id_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['faqs_id']; ?>" ></span>
						<span id="<?php echo 'stars_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['rating_stars']; ?>" ></span>
						
						
						<?php if($allowed_rating_customers == 'all' || ($allowed_rating_customers == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>
				
							<?php if(in_array($_faqs['faqs_id'],$faqs_already_rated)): ?>	
									<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="yes" ></span>
							<?php else: ?>
									<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="no" ></span>
							<?php endif; ?>
							
						<?php else: ?>
						
							<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="yes" ></span>
							
						<?php endif; ?>						
						
														
						<div id="<?php echo 'rating_'.$i; ?>" class="rating_container"> </div>
						<br class="clear" />
					</div>
				<?php endif; ?>
			</div>
		
		
		
		</li>	
		<?php endforeach; ?>
	</ul>
	
    </div>
<?php endif; ?>


</div>
 <?php  function getAllTopics()     
     {	
		return $collection = Mage::getModel('faqs/topic')->getCollection()
					->addStoreFilter(Mage::app()->getStore(true)->getId())
					->addFieldToFilter('status',1)
					->setOrder('main_table.topic_order','ASC')
					->getData();
	
        
    }
	?>