<div class="product-img-sml">
<ul class="small-pro">
<li>
<div class="pro-list-small">
<a href="#basic-green3">
<h3>15 X <img src="<?php echo $this->getSkinUrl('images/product_tiny_green.jpg') ?>" alt="PHD Cleanse &mdash; Pure Green" /></h3>
<h4>Pure Green</h4>
</a>
</div>
</li>
<li>
<div class="pro-list-small">
<a href="#basic-yellow-hit1">
<h3>5 X <img src="<?php echo $this->getSkinUrl('images/product_tiny_yellow.jpg') ?>" alt="" /></h3>
<h4>Yellow Hit</h4>
</a>
</div>
</li>
<li>
<div class="pro-list-small">
<a href="#basic-zesty-lemonade">
<h3>5 X <img src="<?php echo $this->getSkinUrl('images/product_tiny_silver.jpg') ?>" alt="" /></h3>
<h4>Zesty Lemonade</h4>
</a>
</div>
</li>
<li>
<div class="pro-list-small">
<a href="#basic-cashew-dream1">
<h3>5 X <img src="<?php echo $this->getSkinUrl('images/product_tiny_white.jpg') ?>" alt="" /></h3>
<h4>Cashew Dream</h4>
</a>
</div>
</li>
</ul>
</div>