<div class="featured-box">
<h2 class="blue">Cleanse With Friends</h2>
<p><a href="{{store url='phd-group'}}"><img src="{{skin url='images/cleanse-with-friends-start-today.jpg'}}" alt="PHD Group" /></a></p>
<p>Save up to <strong>15% off</strong> by getting your friends and collegues to join you.</p>
<p class="read-butn"><a style="display: block; padding: 11px 27px; text-align: center;" href="{{store url='phd-group'}}">Read More</a></p>
</div>
<div class="featured-box">
<h2 class="pink">About Juice Cleansing</h2>
<p><a href="{{store url='juice-cleansing'}}"><img src="{{skin url='images/about-juice-cleansing.jpg'}}" alt="Juice Cleansing" width="220" height="130" /></a></p>
<p>Feel rejuvenated &amp; energised - discover the benefits of <strong>raw juice cleansing</strong>...</p>
<p class="read-butn"><a style="display: block; padding: 11px 27px; text-align: center;" href="{{store url='juice-cleansing'}}">Read More</a></p>
</div>
<div class="featured-box">
<h2>Pure Health Rewards</h2>
<p><a href="{{store url='rewards'}}"><img src="{{media url="wysiwyg/home_3_order.jpg"}}" alt="Pure Health Rewards" /></a></p>
<p>We think it is only fair that we reward you for your loyalty!</p>
<p class="read-butn"><a style="display: block; padding: 11px 27px; text-align: center;" href="{{store url='rewards'}}">Read More</a></p>
</div>


<div id="latest-facebok" class="">
    <h2><?php echo $this->__('Latest From Facebook') ?></h2>
    <div class="footer-facebook">&nbsp;</div>
    <p class="more-facebook"><a href="http://www.facebook.com/PhdCleanse" target="_blank"><?php echo $this->__('View more on ') ?>
            <img src="<?php echo $this->getSkinUrl('images/facebook_logo.jpg') ?>" alt="Facebook" width="75px" />
        </a></p>
</div>
